# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."medusa" = {
    image = "lscr.io/linuxserver/medusa:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/New_York";
    };
    volumes = [
      "/HD/HD1/Media:/Media:rw"
      "/HD/HD1/TV:/tv:rw"
      "/HD/HD2/Config/Medusa:/config:rw"
      "/HD/HD2/Torrent:/data:rw"
    ];
    ports = [
      "192.168.1.3:9480:8081/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=medusa"
      "--network=medusa_default"
    ];
  };
  systemd.services."docker-medusa" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-medusa_default.service"
    ];
    requires = [
      "docker-network-medusa_default.service"
    ];
    partOf = [
      "docker-compose-medusa-root.target"
    ];
    wantedBy = [
      "docker-compose-medusa-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-medusa_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f medusa_default";
    };
    script = ''
      docker network inspect medusa_default || docker network create medusa_default
    '';
    partOf = [ "docker-compose-medusa-root.target" ];
    wantedBy = [ "docker-compose-medusa-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-medusa-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
