# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."nginx" = {
    image = "lscr.io/linuxserver/nginx:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/HD/HD2/Config/nginx:/config:rw"
    ];
    ports = [
      "80:80/tcp"
      "443:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=nginx"
      "--network=prowlar_default"
    ];
  };
  systemd.services."docker-nginx" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-prowlar_default.service"
    ];
    requires = [
      "docker-network-prowlar_default.service"
    ];
    partOf = [
      "docker-compose-prowlar-root.target"
    ];
    wantedBy = [
      "docker-compose-prowlar-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-prowlar_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f prowlar_default";
    };
    script = ''
      docker network inspect prowlar_default || docker network create prowlar_default
    '';
    partOf = [ "docker-compose-prowlar-root.target" ];
    wantedBy = [ "docker-compose-prowlar-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-prowlar-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
