# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  
  virtualisation.oci-containers.containers."prowlarr" = {
    image = "lscr.io/linuxserver/prowlarr:latest";
    environment = {
      "PGID" = "1001";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/HD/HD2/Config/prowlarr/:/config:rw"
    ];
    ports = [
      "9696:9696/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=prowlarr"
      "--network=prowlarr_default"
    ];
  };
  systemd.services."docker-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-prowlarr_default.service"
    ];
    requires = [
      "docker-network-prowlarr_default.service"
    ];
    partOf = [
      "docker-compose-prowlarr-root.target"
    ];
    wantedBy = [
      "docker-compose-prowlarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-prowlarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f prowlarr_default";
    };
    script = ''
      docker network inspect prowlarr_default || docker network create prowlarr_default
    '';
    partOf = [ "docker-compose-prowlarr-root.target" ];
    wantedBy = [ "docker-compose-prowlarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-prowlarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
