# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."adguardhome" = {
    image = "adguard/adguardhome";
    volumes = [
      "/HD/HD2/Config/adguardhome/confdir:/opt/adguardhome/conf:rw"
      "/HD/HD2/Config/adguardhome/workdir:/opt/adguardhome/work:rw"
    ];
    ports = [
      "53:53/tcp"
      "53:53/udp"
      "67:67/udp"
      "68:68/udp"
      "80:80/tcp"
      "443:443/tcp"
      "443:443/udp"
      "3000:3000/tcp"
      "853:853/tcp"
      "853:853/udp"
      "5443:5443/tcp"
      "5443:5443/udp"
      "6060:6060/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=adguardhome"
      "--network=adguard_default"
    ];
  };
  systemd.services."docker-adguardhome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-adguard_default.service"
    ];
    requires = [
      "docker-network-adguard_default.service"
    ];
    partOf = [
      "docker-compose-adguard-root.target"
    ];
    wantedBy = [
      "docker-compose-adguard-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-adguard_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f adguard_default";
    };
    script = ''
      docker network inspect adguard_default || docker network create adguard_default
    '';
    partOf = [ "docker-compose-adguard-root.target" ];
    wantedBy = [ "docker-compose-adguard-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-adguard-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
